### ISSUE TITLE
Title Case

### ISSUE THREAD

**Issue by maiermic** [silvasur/idea_caseconv#1]
Please add an action to convert to Title Case (for example from `title case` to `Title Case`).

**Comment by silvasur** [comment]
Good idea.

I have a question though, with Title Case do you mean capitalizing every first letter of every word (version a)? There also seems to be a [definition of Title Case](https://en.wikipedia.org/wiki/Letter_case#Title_case) that does have certain exceptions (version b).

a) The Quick Brown Fox Jumps **Over The** Lazy Dog

vs

b) The Quick Brown Fox Jumps **over the** Lazy Dog

**Comment by maiermic** [comment]
I mean capitalizing every first letter (version a).

**Comment by silvasur** [comment]
Done. Commit 88f205aab9167 introduces a new Title Case action.

The new plugin version was submitted to the plugin repository, might take a couple of days to get approved. Will report back, when it's been approved.

**Comment by silvasur** [comment]
The new version was approved. It should appear as an update the next time your IDE checks for updates.

**Comment by maiermic** [comment]
Thanks, works like a charm :+1:
