### ISSUE TITLE
Treat newline as a phrase separator (a.k.a. do not trim newline)

### ISSUE THREAD

**Issue by vanjad-sixt** [silvasur/idea_caseconv#2]
When selecting multiple phrases, separated by newlines and converting, it removes the newlines.

**When:**
```
{selectionStart}aWord
ofCaution
whenSelecting
multiLines{selectionEnd}
```
Select menu: Edit -> Convert case -> Pascal Case
**Expected:**
```
AWord
OfCaution
WhenSelecting
MultiLines
```
**Actual:**
```
AWordOfCautionWhenSelectingMultiLines
```

**Workaround:**
Selecting multiple lines in column mode works as expected:

**When:**

Select menu: Edit -> Column selection mode

```
{selectionStart}aWord{selectionEnd}
{selectionStart}ofCaution{selectionEnd}
{selectionStart}whenSelecting{selectionEnd}
{selectionStart}multiLines{selectionEnd}
```

Select menu: Edit -> Convert case -> Pascal Case

**Result (as expected):**
```
AWord
OfCaution
WhenSelecting
MultiLines
```

Using newline separator: LF (\n)

**Comment by silvasur** [comment]
I guess I've never stumbled over this, because I heavily use multiple cursors, so I would have done that with column select without thinking about it further :D.

But I agree, that your suggested behavior would be better. However, this would break the old behavior some users might rely upon. So I think this should be a configuration option. I'll need to find out how to implement that (I know some plugins do have a page in the settings dialog, so it is possible).

I'll take a closer look this weekend.

**Comment by silvasur** [comment]
This is now implemented with commit d462bbd :tada: 

There is now a new page in the settings window. You can find it under Tools > Case conversion. There you can configure "Treat newline as". Default is "White space" which is the old behavior. The new behavior is called "Record separator".

![Screenshot_2020-10-04_11-35-45](https://user-images.githubusercontent.com/357232/95012144-30b37500-0636-11eb-80b0-980eab92e184.png)

This commit is included in version 0.7.0, which I've just uploaded to the JetBrains plugin repo, so it should arrive via auto-update in the next couple of days.

**Comment by vanjad-sixt** [comment]
Good idea. Also, I didn't expect to see the updates so fast. Thank you!

**Comment by silvasur** [comment]
> Also, I didn't expect to see the updates so fast.

Turns out, once you find the documentation for how to add a custom settings section (<https://jetbrains.org/intellij/sdk/docs/basics/settings.html>) it's actually not that hard to implement, fortunately.

> Thank you!

You're welcome :)
