### ISSUE TITLE
Add Sentence case

### ISSUE THREAD

**Issue by vanjad-sixt** [silvasur/idea_caseconv#3]
Title Case is awesome! It is often overlooked by other plugins.

It's just a feeling that the plugin would be complete by adding the "Sentence case" option.

Great plugin, kudos!

**Comment by silvasur** [comment]
> It's just a feeling that the plugin would be complete by adding the "Sentence case" option.

I agree. I added "Sentence case" with commit 1d07f7b. I've uploaded the new version 0.6.2 to JetBrains plugin repository, so it should be arriving in auto update soon.

> Great plugin, kudos!

Thank you, glad you like it :).
