### ISSUE TITLE
No option to treat any whitespace as record separator

### ISSUE THREAD

**Issue by olliechick** [silvasur/idea_caseconv#5]
My use case is I have a TypeScript class, for example:

```typescript
class Person {
    id: number;
    first_name: string;
    last_name: string;
}
```

I want to convert it to a different case, say camelCase. Currently if I highlight my properties and try to convert them to camel case, the result is:

```typescript
class Person {
id:Number;
firstName:String;
lastName:String;
}
```

However, I obviously don't want the types' case to be converted (it is fine if they are converted separately to camel case). The result should be:

```typescript
class Person {
id:number;
firstName:string;
lastName:string;
}
```

Allowing me to treat each whitespace-separated word as a separate variable would solve this.

**Comment by silvasur** [comment]
I think a better way would be to use the multi caret feature of Intellij here. Either by holding Control and selecting each class member name with the mouse or by using the column selection mode. That way you have the following selections (marked by `[` and `]` below):

```
class Person {
    [id]: number;
    [first_name]: string;
    [last_name]: string;
}
```

If you then invoke the camelCase conversion, you'll get the desired result.

Would that solve your problem?

https://user-images.githubusercontent.com/357232/106520567-4437f500-64dd-11eb-8c91-f9851eed80a4.mp4

**Comment by olliechick** [comment]
oh, yes it would, thanks!
